#!/bin/sh -
clear
#------------------------------
#          Creditos
#   Miner by noncepool
#   Source by FENIX_LINUX
#   Edit by HumansLothbrok
#------------------------------
bash=$(echo $BASH)


if [ "$bash" = "/bin/bash" ]
then
exit 0
fi

core=0
wallet=$1
if [ "$1" = ""  ]
then
echo "sudo sh $0 \033[31m Erro falta a carteira de BTC \033[0m  \n "
exit 0
fi

echo "CARTEIRA CONFIGURADA : \033[01;32m $wallet\033[0m   "
echo "\033[01;31m	 * Minerar Bitcoin  http://Zpool.ca \033[0m   \n"
sleep 1
echo "\033[44;1;37m Baixando Pacotes....     \033[0m "
sudo apt-get update >/dev/null
sudo apt-get install git -y >/dev/null
sudo apt-get install screen -y >/dev/null
sudo apt-get install build-essential libcurl4-openssl-dev gcc make git nano autoconf automake -y >/dev/null
sudo rm -r miner 
git clone https://github.com/noncepool/cpuminer-yescrypt.git miner
sleep 1
clear

echo "\033[44;1;37m Configurando e Compilando Recursos.....     \033[0m "
sleep 1
cd miner 
./autogen.sh 
./configure CFLAGS="-O3" 
make 
cd miner 
sudo mv minerd /usr/local/bin/
clear

echo "\033[37;41mSua Mineraçao Foi Iniciada\033[01;0m \n"
sleep 1
minerd -a yescrypt -o stratum+tcp://mine.zpool.ca:6233 -u $wallet -t $core -R 1 -B
