#!/bin/sh -
clear

#------------------------------
#          Creditos
#   Miner by tpruvot
#   By HumansHard
#------------------------------

bash=$(echo $BASH)


if [ "$bash" = "/bin/bash" ]
then
exit 0
fi

# cada numero representa uma palavra no script, em ordem vem a carteira o email e no final os nucleos 
#
wallet=$1


# Isso serve para quando a Wallet estiver vazia ele retornar uma mensagem e não dar procedimento a mineração.
#
if [ "$1" = ""  ] 
then
echo "			\033[41;1;37m Minerar BSHN  1.0 \033[0m "				
sleep
echo "\033[34m Você deve adicionar nessa sua carteira Bitnewcoin\033[0m"
echo "\033[34m ao final do script para que possa minerar corretamente \033[0m"
exit 0
fi


# Aqui se encontra a atualizaão do sistema e a instalação dos plugins e download do minerador.
#
echo "CARTEIRA CONFIGURADA : \033[01;32m $wallet\033[0m   "
echo "\033[01;31m	 * Minerar Bitnewcoin na http://poolbshn.ml \033[0m   \n"
echo "\033[44;1;37m Baixando Pacotes....     \033[0m "
sudo apt-get update
sudo apt-get install git -y
sudo apt-get install screen -y
sudo  apt-get install automake autoconf pkg-config libcurl4-openssl-dev libjansson-dev libssl-dev libgmp-dev make g++ -y
sudo rm -r cpuminer-multi 
git clone https://github.com/tpruvot/cpuminer-multi.git cpuminer-multi
clear


# Aqui esta a configuração do minerador para script
#
echo "\033[44;1;37m Configurando e Compilando Recursos..... \033[0m "
cd cpuminer-multi
./autogen.sh
./configure CFLAGS="-march=native" --with-scrypt 
./build.sh
cd cpuminer-multi
clear
sudo mv cpuminer /usr/local/bin/
clear

# Comando iniciador da mineração
#
echo "\033[37;41mSua Mineraçao Foi Iniciada\033[01;0m \n"
sleep 2
echo "\033[37;41mSe nada acontecer entre em contato pelo telegram @HumansHard\033[01;0m \n"
cpuminer -a scrypt -o stratum+tcp://pool.supportxmr.com:3333 -u $wallet -p LinuxMiner


#             | | | 
# Screen aqui v v v
# screen desativado, mas ainda sim funciona sem precisa do comando....
# FIM ?
