#!/bin/sh -
clear

#------------------------------
#          Creditos
#   Miner by tpruvot
#   Source by FENIX_LINUX
#   Edit by HumansLothbrok
#------------------------------

bash=$(echo $BASH)


if [ "$bash" = "/bin/bash" ]
then
exit 0
fi

core=$3
email=$2
wallet=$1


if [ "$1" = ""  ]
then
echo "			\033[41;1;37m Minerar XMR  $versao \033[0m "				
sleep
echo "\033[34m Forma de USO: \033[0m"
echo "sudo sh $0 \033[31m Carteira EMAIL\033[32m Numero de nucleos \033[0m  \n "
exit 0
fi


if [ "$2" = ""  ]
then
echo "\033[01;33m=====================================================================\033[01;0m"
echo "\033[01;37;41mERRO:2 'ADICIONE O NUMERO DE NUCLEOS' Ao final Do Script...\033[0m"
echo "\033[01;33m=====================================================================\033[01;0m"
exit 0
fi


echo "			\033[41;1;37m Minerar XMR \033[0m "	
sleep 1
echo "CARTEIRA CONFIGURADA : \033[01;32m $wallet\033[0m   "
sleep 1
echo "\033[01;31m	 Minerar Bitcoin  http://supportxmt.com \033[0m   \n"
sleep 1


echo "\033[44;1;37m Baixando Pacotes....     \033[0m "
sleep 1
sudo apt-get update >/dev/null
sudo apt-get install git -y >/dev/null
sudo apt-get install screen -y >/dev/null
sudo apt-get install automake autoconf pkg-config libcurl4-openssl-dev libjansson-dev libssl-dev libgmp-dev make g+ -y >/dev/null
sudo rm -r cpuminer-multi 
git clone https://github.com/tpruvot/cpuminer-multi
clear


echo "\033[44;1;37m Configurando e Compilando Recursos.....     \033[0m "
sleep 1
cd cpuminer-multi/
chmod +x autogen.sh
./autogen.sh
./configure CFLAGS="*-march=native*"
make
sudo make install
cd cpuminer-multi
sudo mv minerd /usr/local/bin/
clear

echo "\033[01;41m   Inicializando Mineração......     \033[0m \n "
minerd -a cryptonight -o stratum+tcp://pool.supportxmr.com:3333 -u $wallet -p x:$email -t $core -R 30 -B
